name: FrontEnd
description: Web server that interacts with Slack

setup: npm install --loglevel error --depth 0
startup:
  command: node app
  online-text: HTML server is running

messages:
  sends:
  receives:
